### ISSUE TITLE
Should use build_matrix for travis

### ISSUE THREAD

**Issue by nickvergessen** [owncloud/web_hooks#18]
```
env:
  ...
  matrix:
    - DB=sqlite
```

together with

```
matrix:
  include:
    - php: 5.4
      env: DB=mysql
    - php: 5.4
      env: DB=pgsql
    - php: 5.4
      env: DB=oracle
  fast_finish: true
```

To only test non-sqlite once
